### ISSUE TITLE
Inconsistent catalog indirect reference and object number 

### ISSUE THREAD

**Issue by asciim0** [openpreserve/jhove#208]
The document catalog is referenced as an indirect object in the /Root key value pair of the trailer. However, this reference does not seem to be cross-checked with the actual object number of the document catalog. Test case T02-01_002 from the ipres test corpus points to object 5 in the trailer /Root entry, however, the document catalog number has been changed to 6. The file cannot be rendered by Adobe Acrobat but JHOVE considers it well-formed and valid.

**Comment by carlwilson** [comment]
This is caused by a nasty assumption and some equally nasty behaviour, that may be an attempt at mitigation. The problem lies in the [PdfModule class' getObject method](https://github.com/openpreserve/jhove/blob/integration/jhove-modules/src/main/java/edu/harvard/hul/ois/jhove/module/PdfModule.java#L2675). This takes the index of the object to retrieve as the first parameter `objIndex`. When looking up the document catalog the Indirect Object reference found in the trailer for the Root key, in this case `/Root 5 0 R`, is used. The `PdfModule.getObject(int objIndex, int recGuard)` method uses the index value to look up the object offset in an array that's populated with the objects found when parsing the document. In this case the array entry at `[5]` is the catalog object with ID 06.

So much for the assumption, here comes the nasty behaviour at the [end of the getObject method](https://github.com/openpreserve/jhove/blob/integration/jhove-modules/src/main/java/edu/harvard/hul/ois/jhove/module/PdfModule.java#L2733). Here the retrieved object has its ID overwritten with the passed index, in this case setting the ID of the returned object to match the passed id 05. I have an idea of a hack to fix this, expect a PR by the morning (15/03/18).
