### ISSUE TITLE
Optimise packaging of shell and batch execution scripts.

### ISSUE THREAD

**Issue by carlwilson** [openpreserve/jhove#30]
The izpack installer in the [jhove-installer module](https://github.com/openpreserve/jhove/tree/integration/jhove-installer) currently batches the execution scripts in a [single directory](https://github.com/openpreserve/jhove/tree/integration/jhove-installer/src/main/scripts). The [installer configuration](https://github.com/openpreserve/jhove/blob/integration/jhove-installer/src/main/izpack/install.xml) then copies and templates the files one by one.

Split the script files into OS-specific directories, e.g. `src\main\scripts\windows`, etc., then use izpacks filesets to copy and template by OS specific batch.

**Comment by bitsgalore** [comment]
Hi Carl,

Just by chance I was trying to get the Linux launcher script working, and then saw you made some changes  earlier today here: 

https://github.com/openpreserve/jhove/blob/integration/jhove-installer/src/main/scripts/jhove

Not sure if this helps, but instead of:

```
JHOVE_HOME=%INSTALL_PATH
```

You could also use this:

```
JHOVE_HOME="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
```

Which might simplify things, because it eliminates the dependency on `%INSTALL_PATH` (it's not clear to me where this is is set), and the script will work out of the box. Only caveat is that this doesn't work in `sh`, so you'd need to change `#!bin/sh` to `#!bin/bash`.

Ditto for the other scripts that use `JHOVE_HOME`.
