### ISSUE TITLE
xml premature end of file error

### ISSUE THREAD

**Issue by asciim0** [openpreserve/jhove#346]
## Dev Effort
3D

## Description
I'm getting an "premature end of file" error resulting in a not-well formed outcome with the xml-module on the attached file. I can't quite understand why and the file validates fine against other XML validators (like altova).
am I missing something or is this a bug?
[abby_00000001.zip](https://github.com/openpreserve/jhove/files/2013704/abby_00000001.zip)

**Comment by marhop** [comment]
Hi Micky,

I think the problem is caused by the schemaLocation URL in line 2 of your XML file. It says the schema file for the namespace used in this XML document can be found at <http://www.abbyy.com/FineReader_xml/FineReader10-schema-v1.xml>. This URL leads to a redirect (HTTP 301) to <https://www.abbyy.com/FineReader_xml/FineReader10-schema-v1.xml>, the same URL but with HTTPS instead of HTTP. And *this* URL leads to a redirect to <http://fr7.abbyy.com/FineReader_xml/FineReader10-schema-v1.xml>.

If you replace the second URL in the schemaLocation attribute of your XML file by the final URL <http://fr7.abbyy.com/FineReader_xml/FineReader10-schema-v1.xml> validation works like a charm.

I don't know what exactly irritates JHOVE (or rather the XML parser used by JHOVE) here. Maybe it's the cascade of redirects, maybe it's some problem with the HTTPS connection? FWIW, I get the same problems with xmllint, it works only with the final URL, not with the one mentioned in the XML file. So this works:

    xmllint --noout --load-trace --schema http://fr7.abbyy.com/FineReader_xml/FineReader10-schema-v1.xml abby_00000001.xml

But this does not:

    xmllint --noout --load-trace --schema http://www.abbyy.com/FineReader_xml/FineReader10-schema-v1.xml abby_00000001.xml

Hope that helps,
Martin

**Comment by carlwilson** [comment]
Hi both, I agree with Martin's suspicions that there's something rotten with JHOVE's handling of external schema. This issue may be related #312, I'm planning to look closely at this for the next release to at least add the resources mentioned in the issue (hot fix?) and ideally address the exception handling around schema downloads and improve the caching.

**Comment by marhop** [comment]
Also maybe remotely related, or at least worth a look while you're at it: #314.
