### ISSUE TITLE
Switch statements should have a default label

### ISSUE THREAD

**Issue by carlwilson** [openpreserve/jhove#422]
There are 12 occurrences of this issue.
Why is this an issue?
Since: PMD 1.0

All switch statements should include a default option to catch any unspecified values.

Example(s):
```java
public void bar() {
    int x = 2;
    switch (x) {
      case 1: int j = 6;
      case 2: int j = 8;
      				// missing default: here
    }
}
```
A full list of occurrences on codacy can be [found here](https://app.codacy.com/app/openpreserve/jhove/issues?bid=3402463&filters=W3siaWQiOiJMYW5ndWFnZSIsInZhbHVlcyI6W251bGxdfSx7ImlkIjoiQ2F0ZWdvcnkiLCJ2YWx1ZXMiOlsiRXJyb3JQcm9uZSJdfSx7ImlkIjoiTGV2ZWwiLCJ2YWx1ZXMiOltudWxsXX0seyJpZCI6IlBhdHRlcm4iLCJ2YWx1ZXMiOls4OTFdfSx7ImlkIjoiQXV0aG9yIiwidmFsdWVzIjpbbnVsbF19XQ==)

**Comment by nvanderperren** [comment]
I will clean this one now! 🚿

**Comment by nvanderperren** [comment]
@carlwilson some errors in TextHandler.java of Jhove Core module: `reference to Module is ambiguous. both interface edu.harvard.hul.ois.jhove.Module in edu.harvard.hul.ois.jhove and class java.lang.Module in java.lang match`. Also errors of overridden methods that are not overriden.

Do I make a seperate issue of this? not sure if this is an important error or class...

**Comment by tledoux** [comment]
Hi @nvanderperren, the errors about the ambiguous `Module` class come from the fact that you use a Java 9.0 or greater to compile Jhove. Indeed this version of Java introduced the notion of modules at the core of the language which hits the use of Module by Jhove. The easy fix is just to desambiguate using the full name each time it is refered to.

We definitively need to fix this in order to remain compatible. A separated issue will probably be better to handle it.

**Comment by nvanderperren** [comment]
Ok, I create a separate issue.

Op di 22 okt. 2019 09:28 schreef tledoux <notifications@github.com>:

**Comment by carlwilson** [comment]
@nvanderperren many thanks for this, the switch default clean up was on my list for this week. I can see where the issue has arisen regarding use of module but that is another issue. Thanks again.
