### ISSUE TITLE
Javadoc error at Long in WARC module

### ISSUE THREAD

**Issue by RvanVeenendaal** [openpreserve/jhove#584]
At Long, https://github.com/openpreserve/jhove/blob/7a277f8f888a73e0074abbdd85faa2360fdcc1a8/jhove-ext-modules/src/main/java/edu/harvard/hul/ois/jhove/module/warc/WarcRecordProperties.java#L226 the Javadoc mentions "not null and not empty", but the source code only checks the first condition, which I think is correct. I.e. update the Javadoc.

**Comment by carlwilson** [comment]
Thanks @RvanVeenendaal, I'm adding this to the dev hackathon list.

**Comment by carlwilson** [comment]
So @RvanVeenendaal this is intriguing. The code has changed since the commit you're highlighting, and it now matches the JavaDoc. The [source history](https://github.com/openpreserve/jhove/commits/integration/jhove-ext-modules/src/main/java/edu/harvard/hul/ois/jhove/module/warc/WarcRecordProperties.java) is bizarre; there's no commit highlighted as making the change, [it just "appears"](https://github.com/openpreserve/jhove/commit/002c20df2797950af7656f56be9100e61688e56d#diff-1b854b6e8f2677a6c246cb71c3965ab0L36), note it's not in the highlighted changes, [but it's there](https://github.com/openpreserve/jhove/blob/002c20df2797950af7656f56be9100e61688e56d/jhove-ext-modules/src/main/java/edu/harvard/hul/ois/jhove/module/warc/WarcRecordProperties.java#L220). Am going to close this but for a different reason.
