### ISSUE TITLE
JHOVE 1.24.2 SecurityException

### ISSUE THREAD

**Issue by tledoux** [openpreserve/jhove#639]
While implementing a Java application using JHove from Maven central, I hit the following error:
`Caused by: java.lang.SecurityException: class "edu.harvard.hul.ois.jhove.module.XmlModule"'s signer information does not match signer information of other classes in the same package`

Indeed, looking at the jars of the modules in maven, it appears that some are **signed** while the previous ones weren't.
This causes the problem for the follwing modules: ascii-hul, utf-8, xml-hul, html-hul.

Furthermore, looking at the depencies on the modules, 3 sets become apparent:

- html -> xml -> utf8 -> ascii
- jpeg -> tiff
- wave > aiff

I wonder if each of those shouldn't be proposed as a whole jar. In particular, the first one could be include in the core (at least, xml, utf8 and ascii) since they seem oblivious.

Last, it would be nice if the  jhove-ext-modules could be handle the same way, so that we can import one without the others.

Cheers
  Thomas

**Comment by asciim0** [comment]
I actually needed to actively exclude the utf8 and ascii-modules via conf file in the pre-compiled version to get JHOVE to run properly. I'm surprised there are not more error reports on this - I thought it was just me until I read you issue, Thomas, which seems to be related (or at least a pointer towards the root cause).

**Comment by marhop** [comment]
Maybe related: #564

**Comment by jackdos** [comment]
We're in limbo a bit on this too. We're currently running 1.20, and can't upgrade to 1.24 because we hit this signing issue, and can't upgrade to 1.22 because of a bug that was fixed in the 1.24 release, so any resolution on this would be helpful.

**Comment by carlwilson** [comment]
Sorry all, this was brought to my attention yesterday. The same security signing that's used for the apps has ended up on the Maven central jars, I'm in the process of getting some JARs without code signing onto Maven central ASAP.

**Comment by carlwilson** [comment]
I believe that a set of 1.24.7 JARs is now built and deployed on Maven central. It might take up to a day before they show in searches but you should all be able to get them on Monday.

**Comment by jackdos** [comment]
Hi Carl, I'm not seeing the 1.24.7 jars in mvnrepository or maven.org, is it expected to take this long to show up?

**Comment by carlwilson** [comment]
Thanks @jackdos it appears something went amiss at that end and no, it should be within a few hours. Am just uploading a new set now (1.24.8) and will sign them off. The most likely explanation is that I inadvertently dropped them rather than release them, but am pretty sure I didn't.

Now I try to release, it appears the problem is at Maven Central. It won't let me release 1.24.8 as I apparently can't update 1.24.8 BUT I agree that's nowhere in the release list on central. Am now trying 1.24.9 to see if that works at least.

**Comment by carlwilson** [comment]
Second update, I see the problem I think will have a run at it this a little later.

**Comment by carlwilson** [comment]
OK @jackdos I have a partial fix for this in place. I suspect that there's still a problem with the main JHOVE modules on Maven but if the the 1.24.9 artefacts on Maven are useable I'll do something to fix the modules:

<https://repo1.maven.org/maven2/org/openpreservation/jhove/jhove-core/1.24.9/>

**Comment by tledoux** [comment]
Hi @carlwilson, I confirm that indeed the 1.24.9 version of jhove-core is visible in maven central and is not signed (as 1.24.2 is).
So it appears your fix works. If you may extend it to the modules, it will definitively solve the issue. Thanks.

**Comment by jackdos** [comment]
Hi @carlwilson, have you been able to re-publish the module jars to address this yet?

Thanks!

**Comment by carlwilson** [comment]
The latest module releases fix this issue.
