### ISSUE TITLE
incorrect validity report on image

### ISSUE THREAD

**Issue by abrin** [openpreserve/jhove#66]
I tested JHOVE2 (1.11) with a "invalid image" (https://bitbucket.org/tdar/tdar.src/src/9c2656809786e6a8730e57e3b71333b9aa5258fd/test-resources/src/main/resources/images/sample_image_formats/grandcanyon_lzw_corrupt.tif?at=default ) It won't open in Photoshop or preview, tiffinfo (libtiff) and identify (imagemagick) both read it as invalid, but jhove seems to report it as "well formed and valid":

```
[abrin@dev jhove]$ ./jhove ~tdar/tdar.src/test-resources/src/main/resources/images/sample_image_formats/grandcanyon_lzw_corrupt.tif 
Mar 15, 2016 9:02:57 AM edu.harvard.hul.ois.jhove.JhoveBase init
SEVERE: Testing SEVERE level
Jhove (Rel. 1.11, 2013-09-29)
 Date: 2016-03-15 09:02:57 MST
 RepresentationInformation: /home/tdar/tdar.src/test-resources/src/main/resources/images/sample_image_formats/grandcanyon_lzw_corrupt.tif
  ReportingModule: BYTESTREAM, Rel. 1.3 (2007-04-10)
  LastModified: 2015-08-30 16:06:33 MST
  Size: 50496
  Format: bytestream
  Status: Well-Formed and valid
  MIMEtype: application/octet-stream


[abrin@dev jhove]$ tiffinfo ~tdar/tdar.src/test-resources/src/main/resources/images/sample_image_formats/grandcanyon_lzw_corrupt.tif 
/home/tdar/tdar.src/test-resources/src/main/resources/images/sample_image_formats/grandcanyon_lzw_corrupt.tif: Not a TIFF or MDI file, bad magic number 24909 (0x614d).
[abrin@dev jhove]$ identify ~tdar/tdar.src/test-resources/src/main/resources/images/sample_image_formats/grandcanyon_lzw_corrupt.tif 
identify.im6: Not a TIFF or MDI file, bad magic number 24909 (0x614d). `/home/tdar/tdar.src/test-resources/src/main/resources/images/sample_image_formats/grandcanyon_lzw_corrupt.tif' @ error/tiff.c/TIFFErrors/508.
```

**Comment by anjackson** [comment]
Note that JHOVE says:

```
Format: bytestream
Status: Well-Formed and valid
```

i.e. it is a valid and well-formed bytestream. This means format identification has failed. It hasn't even tried to run the TIFF module on it, IIRC.

This is one of the most confusing aspects of JHOVE, and we should perhaps consider NOT saying a bytestream is 'valid' or 'well formed' because frankly that doesn't mean much.

**Comment by abrin** [comment]
Thanks.  This makes perfect sense in retrospect.

**Comment by abrin** [comment]
Is there an example somewhere of what JHOVE would output if it was able to identify that a file was a TIFF, but was corrupt or otherwise invalid?  Thanks.

**Comment by gmcgath** [comment]
There are two cases to consider. If the file is "well-formed but not valid," which for the TIFF module means it contains only minor errors, JHOVE will recognize it as a TIFF file. If the file is "not well-formed," then you can still force it to report TIFF errors by telling it to run only the TIFF module (-m TIFF-hul). Otherwise it will fall through to bytestream. I've attached an example of output for a "well-formed but not valid" file (though I'm not really sure that a missing StripByteCounts tag should be considered a minor error).

[jhove_bad_tiff.txt](https://github.com/openpreserve/jhove/files/175130/jhove_bad_tiff.txt)

**Comment by abrin** [comment]
This is very useful — We’re about to send a large number of images through JHOVE, so this will give me something to look for in the output. to start evaluating the results. Thanks.
