### ISSUE TITLE
jhove 1.30.1 reports as jhove 1.30.0

### ISSUE THREAD

**Issue by samalloing** [openpreserve/jhove#933]
Hi @carlwilson 

The new version jHove 1.30.1 shows as jhove 1.30.0 release in the jHove output

![Schermafbeelding 2024-08-07 112250](https://github.com/user-attachments/assets/babc7fb8-df1e-4db9-8dee-3852a62cb8b6)

Sam

**Comment by carlwilson** [comment]
Hi @samalloing, that's because I didn't update `jhove-core` as there was no need to, The `PDF-hul` version has been updated. The GUI should really report the version of the `jhove-apps` project, which is 1.30.1 as is the installer. I suggest we fix the version reported as the apps project always needs updating. We could also add the details of the other libraries.

**Comment by samalloing** [comment]
Hi @carlwilson 

Right, that would be a good solution, becaues it is confusing that the release date is the one from 1.30.1 and the version is the previous version number.

Thanks for looking into this!

Sam

**Comment by carlwilson** [comment]
I'm closing this as the new release makes the problem go away. I've raised this issue so that the problem can be fixed properly #953
