### ISSUE TITLE
JHOVE tested on Windows 11?

### ISSUE THREAD

**Issue by RvanVeenendaal** [openpreserve/jhove#977]
At the National Archives of the Netherlands we will migrate from Windows 10 to Windows 11 early next year.
Do you happen to have tested JHOVE and veraPDF on Windows 11, and could you possibly share ‘proof’ of that?
Together with our ICT provider, we have packaged JHOVE and veraPDF for deployment on our computers.
The migration to Windows 11 would be a good opportunity to also upgrade to the latest JHOVE and veraPDF versions at that time.
It will help this process if we can assure our ICT provider that JHOVE and veraPDF work on Windows 11.

**Comment by tledoux** [comment]
Hi Remco,

please find below a screen copy of my computer under Windows 11 executing Jhove (it's even an old 1.26 version...)
In fact, the main issue is not Jhove itself but Java.
In order to execute Jhove (but veraPDF should be the same) you should first install a Java Runtime. In my case, I install an 
Eclipse  Adoptium Java 21 version.

Hope this helps.

![JHOVE-GUI_Windows11](https://github.com/user-attachments/assets/064a44e0-d296-4b82-a07e-cd5e62d75a4e)

**Comment by RvanVeenendaal** [comment]
Excellent, @tledoux, thanks for your help.
